export const GET_HOSTELS_LOAD = "GET_HOSTELS_LOAD";
export const GET_HOSTELS_SUCCESS = "GET_HOSTELS_SUCCESS";
export const GET_HOSTELS_FAIL = "GET_HOSTELS_FAIL";

export const GET_HOSTEL_LOAD = "GET_HOSTEL_LOAD";
export const GET_HOSTEL_SUCCESS = "GET_HOSTEL_SUCCESS";
export const GET_HOSTEL_FAIL = "GET_HOSTEL_FAIL";

export const DELETE_HOSTEL_SUCCESS = "DELETE_HOSTEL_SUCCESS";
export const DELETE_HOSTEL_FAIL = "DELETE_HOSTEL_FAIL";

export const TOOGLE_TRUE = "TOOGLE_TRUE";
export const TOOGLE_FALSE = "TOOGLE_FALSE";

export const ADD_HOSTEL_SUCCESS = "ADD_HOSTEL_SUCCESS";
export const ADD_HOSTEL_FAIL = "ADD_HOSTEL_FAIL";

export const ADD_HOSTEL_REVIEW_SUCCESS = "ADD_HOSTEL_REVIEW_SUCCESS";
export const ADD_HOSTEL_REVIEW_FAIL = "ADD_HOSTEL_REVIEW_FAIL";
