export const GET_HOTELS_LOAD = "GET_HOTELS_LOAD";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAIL = "GET_HOTELS_FAIL";

export const GET_HOTEL_LOAD = "GET_HOTEL_LOAD";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_FAIL = "GET_HOTEL_FAIL";

export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL";

export const TOOGLE_TRUE = "TOOGLE_TRUE";
export const TOOGLE_FALSE = "TOOGLE_FALSE";

export const ADD_HOTEL_SUCCESS = "ADD_HOTEL_SUCCESS";
export const ADD_HOTEL_FAIL = "ADD_HOTEL_FAIL";

export const ADD_HOTEL_REVIEW_SUCCESS = "ADD_HOTEL_REVIEW_SUCCESS";
export const ADD_HOTEL_REVIEW_FAIL = "ADD_HOTEL_REVIEW_FAIL";

export const UPDATE_SUCC = "UPDATE_SUCC";
export const UPDATE_FAIL = "UPDATE_FAIL";
