export const GET_RESTAURANTS_LOAD = "GET_RESTAURANTS_LOAD";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAIL = "GET_RESTAURANTS_FAIL";

export const GET_RESTAURANT_LOAD = "GET_RESTAURANT_LOAD";
export const GET_RESTAURANT_SUCCESS = "GET_RESTAURANT_SUCCESS";
export const GET_RESTAURANT_FAIL = "GET_RESTAURANT_FAIL";

export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";

export const TOOGLE_TRUE = "TOOGLE_TRUE";
export const TOOGLE_FALSE = "TOOGLE_FALSE";

export const ADD_RESTAURANT_SUCCESS = "ADD_RESTAURANT_SUCCESS";
export const ADD_RESTAURANT_FAIL = "ADD_RESTAURANT_FAIL";

export const ADD_RESTAURANT_REVIEW_SUCCESS = "ADD_RESTAURANT_REVIEW_SUCCESS";
export const ADD_RESTAURANT_REVIEW_FAIL = "ADD_RESTAURANT_REVIEW_FAIL";
